BSHDEV/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('homepage/', include('homepage.urls')),
    path('homepage/', include('django.contrib.auth.urls')),
    path('tech_analysis/', include('tech_analysis.urls')),
    path('user/', include('bsh_user.urls')),
]

bsh_user/urls.py
from django.urls import path
from . import views


app_name = "bsh_user"
urlpatterns = [
    path('Results_Search_user', views.results, name='Results_Search_user'),
    path('Userpage', views.user_page, name='Userpage'),
    path('', views.analysis, name='AnalysisPage'),
]

homepage/urls.py
from django.urls import path
from . import views
from django.conf.urls import url

app_name = "homepage"
urlpatterns = [
    path('', views.homepage, name='Homepage'),
    path('our_goal', views.our_goal, name='Our_Goal'),
    path('our_inspiration', views.our_inspiration, name='Our_Inspiration'),
    path('what_do_we_do', views.what_do_we_do, name='What_do_we_do'),
    path('who_we_are', views.who_we_are, name='Who_we_are'),
    path('registration', views.register, name='Register'),

]

bsh_user/models.py
from django.db import models
from django.contrib.auth.models import User


class WatchList(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    watchlist = models.CharField(max_length=300, default='Explore Stocks and Add them to your watchlist')
    price = models.FloatField(default='')
    signal = models.CharField(max_length=20, default='')

    def __str__(self):
        return self.watchlist

bsh_user/views.py
from django.shortcuts import render, HttpResponse, redirect
from tech_analysis.models import Conames
from bsh_user.models import WatchList
import datetime as dt
from datetime import date
import pandas_datareader.data as web
from typing import List
import requests
from azure.cognitiveservices.search.newssearch import NewsSearchAPI
from azure.cognitiveservices.language.textanalytics import TextAnalyticsClient
from msrest.authentication import CognitiveServicesCredentials
import os
from statistics import mean, mode
import ta


# Create your views here.

def user_page(request):
    start = dt.datetime(2017, 1, 1)
    end = date.today()
    dfn = web.DataReader("^NSEI", 'yahoo', start, end)

    closen = dfn['Close']
    pricen1 = closen[-1]
    pricen2 = closen[-2]
    pdiffn = ((pricen1 - pricen2) / pricen2) * 100
    diffn = "%.2f" % pdiffn
    price_nifty = "%.2f" % pricen1
    if pdiffn > 0:
        diffn_green = "+" + diffn + "%"
    else:
        diffn_green = ""

    if pdiffn < 0:
        diffn_red = diffn + "%"
    else:
        diffn_red = ""

    dfs = web.DataReader("^BSESN", 'yahoo', start, end)
    closes = dfs['Close']
    prices1 = closes[-1]
    prices2 = closes[-2]
    pdiffs = ((prices1 - prices2) / prices2) * 100
    diffs = "%.2f" % pdiffs
    price_sensex = "%.2f" % prices1
    if pdiffs >= 0:
        diffs_green = "+" + diffs + "%"
    else:
        diffs_green = ""

    if pdiffs <= 0:
        diffs_red = diffs + "%"
    else:
        diffs_red = ""

    dfnb = web.DataReader("VAKRANGEE.NS", 'yahoo', start, end)
    closenb = dfnb['Close']
    pricenb1 = closenb[-1]
    pricenb2 = closenb[-2]
    pdiffnb = ((pricenb1 - pricenb2) / pricenb2) * 100
    diffnb = "%.2f" % pdiffnb
    if pdiffnb > 0:
        diffnb_green = "+" + diffnb + "%"
    else:
        diffnb_green = ""

    if pdiffnb < 0:
        diffnb_red = diffnb + "%"
    else:
        diffnb_red = ""
    price_nb = "%.2f" % pricenb1

    rows = []
    if request.method == 'POST':
        form = request.POST.get('Ticker')
        price = request.POST.get('Price')
        signal = request.POST.get('Signal')
        User = request.user
        post = WatchList(user=User, watchlist=form, price=price, signal=signal)
        post.save()
        watchlists = WatchList.objects.filter(user=User)
        closeps = []
        wl = []
        wl_p = []
        wl_sig = []
        for watchlist in watchlists:
            wl.append(watchlist.watchlist)
            wl_p.append(watchlist.price)
            wl_sig.append(watchlist.signal)
            index = Conames.objects.get(Co_name=watchlist).pk
            object_list = Conames.objects.only('ticker').get(pk=index).ticker
            start = dt.datetime(2019, 1, 1)
            end = date.today()
            df = web.DataReader(object_list, 'yahoo', start, end)
            close = df['Close']
            closeps.append("%.2f" % close[-1])
            rows = zip(wl, wl_p, wl_sig, closeps)

        return render(request, 'bsh_user/user_page.html',
                      {'rows': rows, 'price_nifty': price_nifty,
                       'diffn_green': diffn_green, 'diffn_red': diffn_red,
                       'price_sensex': price_sensex,
                       'diffs_red': diffs_red, 'diffs_green': diffs_green,
                       'price_nb': price_nb, 'diffnb_green': diffnb_green,
                       'diffnb_red': diffnb_red, 'name': "Vakrangee Ltd."})

    else:
        user = request.user
        watchlists = WatchList.objects.filter(user=user)
        closeps = []
        wl = []
        wl_p = []
        wl_sig = []
        for watchlist in watchlists:
            wl.append(watchlist.watchlist)
            wl_p.append(watchlist.price)
            wl_sig.append(watchlist.signal)
            object_list = Conames.objects.only('ticker').get(Co_name=watchlist).ticker
            start = dt.datetime(2019, 1, 1)
            end = date.today()
            df = web.DataReader(object_list, 'yahoo', start, end)
            close = df['Close']
            closeps.append("%.2f" % close[-1])
            rows = zip(wl, wl_p, wl_sig, closeps)

        return render(request, 'bsh_user/user_page.html',
                      {'rows': rows, 'price_nifty': price_nifty,
                       'diffn_green': diffn_green, 'diffn_red': diffn_red,
                       'price_sensex': price_sensex,
                       'diffs_red': diffs_red, 'diffs_green': diffs_green,
                       'price_nb': price_nb, 'diffnb_green': diffnb_green,
                       'diffnb_red': diffnb_red, 'name': "Vakrangee Ltd."})

def results(request):

    if request.method == 'GET':
        form = request.GET
        ticker = form.get("Ticker", "0")
        indexs = Conames.objects.filter(Co_name__icontains=ticker)

        start = dt.datetime(2017, 1, 1)
        end = date.today()
        dfn = web.DataReader("^NSEI", 'yahoo', start, end)

        closen = dfn['Close']
        pricen1 = closen[-1]
        pricen2 = closen[-2]
        pdiffn = ((pricen1 - pricen2) / pricen2) * 100
        diffn = "%.2f" % pdiffn
        price_nifty = "%.2f" % pricen1
        if pdiffn > 0:
            diffn_green = "+" + diffn + "%"
        else:
            diffn_green = ""

        if pdiffn < 0:
            diffn_red = diffn + "%"
        else:
            diffn_red = ""

        dfs = web.DataReader("^BSESN", 'yahoo', start, end)
        closes = dfs['Close']
        prices1 = closes[-1]
        prices2 = closes[-2]
        pdiffs = ((prices1 - prices2) / prices2) * 100
        diffs = "%.2f" % pdiffs
        price_sensex = "%.2f" % prices1
        if pdiffs >= 0:
            diffs_green = "+" + diffs + "%"
        else:
            diffs_green = ""

        if pdiffs <= 0:
            diffs_red = diffs + "%"
        else:
            diffs_red = ""

        dfnb = web.DataReader("VAKRANGEE.NS", 'yahoo', start, end)
        closenb = dfnb['Close']
        pricenb1 = closenb[-1]
        pricenb2 = closenb[-2]
        pdiffnb = ((pricenb1 - pricenb2) / pricenb2) * 100
        diffnb = "%.2f" % pdiffnb
        if pdiffnb > 0:
            diffnb_green = "+" + diffnb + "%"
        else:
            diffnb_green = ""

        if pdiffnb < 0:
            diffnb_red = diffnb + "%"
        else:
            diffnb_red = ""
        price_nb = "%.2f" % pricenb1

        return render(request, 'bsh_user/user_page_search.html',
                      {'indexs':indexs, 'price_nifty': price_nifty,
                       'diffn_green': diffn_green, 'diffn_red': diffn_red,
                       'price_sensex': price_sensex,
                       'diffs_red': diffs_red, 'diffs_green': diffs_green,
                       'price_nb': price_nb, 'diffnb_green': diffnb_green,
                       'diffnb_red': diffnb_red, 'name': "Vakrangee Ltd."})

def analysis(request):
    if request.method == 'GET':
        form = request.GET
        ticker = form.get("Ticker", "0")
        co = Conames.objects.get(Co_name=ticker).Co_name
        index = Conames.objects.get(Co_name=ticker).pk
        Y = Conames.objects.only('ticker').get(pk=index).ticker
        X = Conames.objects.only('tick').get(pk=index).tick
        tick = X.upper()
        start = dt.datetime(2017, 1, 1)
        end = date.today()
        df = web.DataReader(Y, 'yahoo', start, end)
        close = df['Close']
        high = df['High']
        low = df['Low']
        volume = df['Volume']
        p = close[-1]
        p1 = close[-2]
        diff = ((p - p1) / p1) * 100
        d = "%.2f" % diff
        if diff > 0:
            diff_green = "+" + d + "%"
        else:
            diff_green = ""

        if diff < 0:
            diff_red = d + "%"
        else:
            diff_red = ""

        price = "%.2f" % p

        def rs():
            r = ta.rsi(close, n=14, fillna=False)
            rsi = (r[-1])
            if 15.1 <= rsi <= 30:
                status = "Buy"
            elif rsi <= 15:
                status = "Strong Buy"
            elif 84.9 <= rsi >= 70:
                status = "Sell"
            elif rsi >= 85:
                status = "Strong Sell"
            else:
                status = "Hold"
            return status

        def ao():
            ao = ta.ao(high, low, s=5, len=34, fillna=False)
            AO = ao[-1]
            A = (ao[-10:])
            if 0 >= AO >= -0.5:
                def order():  # For ascending
                    for i in range(len(A) - 1):
                        if A[i] - A[i + 1] > 0:
                            return False
                        return True

                if order():
                    status1 = "Buy"
                else:
                    status1 = "Sell"

            elif 0 <= AO <= 0.5:
                def order():  # For descending
                    for i in range(len(A) - 1):
                        if A[i] - A[i + 1] < 0:
                            return False
                        return True

                if order():
                    status1 = "Sell"
                else:
                    status1 = "Buy"

            elif AO <= -1:
                status1 = "Buy"
            elif AO >= 1:
                status1 = "Sell"
            else:
                status1 = "Hold"
            return status1

        def mf():
            mfi = ta.money_flow_index(high, low, close, volume, n=14, fillna=False)
            MFI = mean(mfi[-7:])
            if MFI <= 20:
                status2 = "Buy"
            elif MFI <= 30:
                status2 = "Buy"
            elif MFI >= 80:
                status2 = "Sell"
            elif MFI >= 70:
                status2 = "Sell"
            else:
                status2 = "Hold"
            return status2

        def so():
            so = ta.stoch(high, low, close, n=14, fillna=False)
            SO = (so[-1])
            if SO <= 20:
                status3 = "Buy"
            elif SO <= 30:
                status3 = "Buy"

bsh_user/templates/bsh_user/analysis.html
{% extends 'bsh_user/layout_User.html' %}
{% block content %}
    {% load static %}
    <head>

        <link rel="stylesheet" href="https://storage.googleapis.com/bshd_static/static/bsh_user/user_analysis.css">
<meta name="viewport" content="width=device-width" initial-scale="1.0">

        <title>Analysis</title>
    </head>

    <body>
    <div class="insert_ticker">
     <form action={% url 'bsh_user:Results_Search_user' %} method="get" autocomplete="on">
         <div class="autocomplete">

            <label>
                <input class="enter_ticker" type="text" name="Ticker" id="myInput"  placeholder="Enter Ticker">
                <img class="search-label-icon" src="https://storage.googleapis.com/bshd_static/static/homepage/path.png" alt="search" id="input_img">
            </label>
            <input class="technical_analysis" type="image" src="https://storage.googleapis.com/bshd_static/static/homepage/Submit.png" >
            </div>
        </form>
</div>
    <div class="line"></div>
    <div class="co_name">
        <ul class="ticker_table">
            <li class="ticker_name">{{ ticker }}-</li>
            <li class="ticker_price">{{ price }}</li>
            <li class="diff_green">{{ diff_green }}</li>
            <li class="diff_red">{{ diff_red }}</li>
        </ul></div>

    <div class="watchlist"> <form action="{% url 'bsh_user:Userpage' %}" method="post">
            {% csrf_token %}
            <label>
                <input class="watchlist" type="hidden" name="Ticker" value="{{ ticker }}">
            </label>
             <label>
                <input class="watchlist" type="hidden" name="Price" value="{{ price }}">
            </label>
            <label>
                <input class="watchlist" type="hidden" name="Signal" value="{{ signal }}">
            </label>
            <input class="watchlist" type="submit" name="add to watchlist" value="Add to Watchlist+">
        </form> </div>


    <div class="tradingview-widget-container">
        <div id="tradingview_b76bd"></div>
        <div class="tradingview-widget-copyright"><a href="https://in.tradingview.com/symbols/"
                                                     rel="noopener" target="_blank"> </a></div>
        <script type="text/javascript" src="https://s3.tradingview.com/tv.js"></script>
        <script type="text/javascript">
            new TradingView.widget(
                {
                    "width": 1850,
                    "height": 740,
                    "symbol": "BSE:{{ x }}",
                    "interval": "D",
                    "timezone": "Asia/Kolkata",
                    "theme": "Dark",
                    "style": "1",
                    "locale": "in",
                    "toolbar_bg": "#f1f3f6",
                    "enable_publishing": false,
                    "allow_symbol_change": false,
                    "container_id": ""
                }
            );
        </script>
    </div>
     <div class="tradingview-widget-container-laptop">
        <div id="tradingview_b76bd"></div>
        <div class="tradingview-widget-copyright"><a href="https://in.tradingview.com/symbols/"
                                                     rel="noopener" target="_blank"> </a></div>
        <script type="text/javascript" src="https://s3.tradingview.com/tv.js"></script>
        <script type="text/javascript">
            new TradingView.widget(
                {
                    "width": 1200,
                    "height": 630,
                    "symbol": "BSE:{{ x }}",
                    "interval": "D",
                    "timezone": "Asia/Kolkata",
                    "theme": "Dark",
                    "style": "1",
                    "locale": "in",
                    "toolbar_bg": "#f1f3f6",
                    "enable_publishing": false,
                    "allow_symbol_change": false,
                    "container_id": ""
                }
            );
        </script>
    </div>
    <div class="tradingview-widget-container-mobile-iphone6">
        <div id="tradingview_b76bd"></div>
        <div class="tradingview-widget-copyright"><a href="https://in.tradingview.com/symbols/"
                                                     rel="noopener" target="_blank"> </a></div>
        <script type="text/javascript" src="https://s3.tradingview.com/tv.js"></script>
        <script type="text/javascript">
            new TradingView.widget(
                {
                    "width": 360,
                    "height": 500,
                    "symbol": "BSE:{{ x }}",
                    "interval": "D",
                    "timezone": "Asia/Kolkata",
                    "theme": "Light",
                    "style": "2",
                    "locale": "in",
                    "toolbar_bg": "#f1f3f6",
                    "enable_publishing": false,
                    "allow_symbol_change": false,
                    "container_id": ""
                }
            );
        </script>
    </div>
    <div class="tradingview-widget-container-mobile-onp5">
        <div id="tradingview_b76bd"></div>
        <div class="tradingview-widget-copyright"><a href="https://in.tradingview.com/symbols/"
                                                     rel="noopener" target="_blank"> </a></div>
        <script type="text/javascript" src="https://s3.tradingview.com/tv.js"></script>
        <script type="text/javascript">
            new TradingView.widget(
                {
                    "width": 420,
                    "height": 600,
                    "symbol": "BSE:{{ x }}",
                    "interval": "D",
                    "timezone": "Asia/Kolkata",
                    "theme": "Light",
                    "style": "2",
                    "locale": "in",
                    "toolbar_bg": "#f1f3f6",
                    "enable_publishing": false,
                    "allow_symbol_change": false,
                    "container_id": ""
                }
            );
        </script>
    </div>
    <div class="news_sentiment">
        <div class="news_trend">News Trend-</div>
        <div class="news_trend_percentage">
            <ul class="percentage_table">
                <li class="buy">{{ news_buy }}</li>
                <li class="sell">{{ news_sell }}</li>
                <li class="hold">{{ news_hold }}</li>
            </ul> </div>
    </div>
    <div class="line"></div>
    <div class="head">
        Technical Analysis
    </div>
    <div class="coname">
    <div class="tables">
        <table class="momentum">
            <tr>
                <th>Momentum</th>
                <th>Signal</th>
            </tr>
            <tr>
                <td class="fisrt">Relative Strength Index</td>
                <td class="second"> {{ mom_rsi }} </td>
            </tr>
            <tr>
                <td class="fisrt">Awesome Oscillator</td>
                <td class="second"> {{ mom_ao }}</td>
            </tr>
            <tr>
                <td class="fisrt">Money Flow Index</td>
                <td class="second"> {{ mom_mf }}</td>
            </tr>
            <tr>
                <td class="fisrt">Stochastic Oscillator</td>
                <td class="second"> {{ mom_so }}</td>
            </tr>
            <tr>
                <td class="fisrt">True Strength Index</td>
                <td class="second"> {{ mom_tsi }}</td>
            </tr>
            <tr>
                <td class="fisrt">Ultimate Oscillator</td>
                <td class="second"> {{ mom_uo }}</td>
            </tr>
            <tr>
                <td class="fisrt">Williams %R</td>
                <td class="second"> {{ mom_wr }}</td>
            </tr>

        </table>

        <table class="Volume">
            <tr>
                <th>Volume</th>
                <th>Signal</th>
            </tr>
            <tr>
                <td class="fisrt">Chaikin Money Flow</td>
                <td class="second"> {{ vol_cm }}</td>
            </tr>
            <tr>
                <td class="fisrt">Ease of movement</td>
                <td class="second"> {{ vol_em }}</td>
            </tr>
            <tr>
                <td class="fisrt">Force Index</td>
                <td class="second"> {{ vol_fi }}</td>
            </tr>
            <tr>
                <td class="fisrt">Negative Volume Index</td>
                <td class="second"> {{ vol_nv }}</td>
            </tr>
            <tr>
                <td class="fisrt">On-balance volume</td>
                <td class="second"> {{ vol_ob }}</td>
            </tr>
            <tr>
                <td class="fisrt">Accumulation/Distribution Index</td>
                <td class="second"> {{ vol_adi }}</td>
            </tr>
        </table>


        <table class="Volatility">
            <tr>
                <th>Volatility</th>
                <th>Signal</th>
            </tr>
            <tr>
                <td class="fisrt">Average True Range</td>
                <td class="second"> {{ vot_atr }}</td>
            </tr>
            <tr>
                <td class="fisrt">Bollinger Bands</td>
                <td class="second"> {{ vot_bb }}</td>
            </tr>
            <tr>
                <td class="fisrt">Donchian channel</td>
                <td class="second"> {{ vot_dch }}</td>
            </tr>
        </table>

        <table class="Trend">
            <tr>
                <th>Trend</th>
                <th>Signal</th>
            </tr>
            <tr>
                <td class="fisrt">Average Directional Movement Index</td>
                <td class="second"> {{ trn_adx }}</td>
            </tr>
            <tr>
                <td class="fisrt">Aroon Indicator</td>
                <td class="second"> {{ trn_ai }}</td>
            </tr>
            <tr>
                <td class="fisrt">Commodity Channel Index</td>
                <td class="second"> {{ trn_cci }}</td>
            </tr>
            <tr>
                <td class="fisrt">Detrended Price Oscillator</td>
                <td class="second"> {{ trn_dpo }}</td>
            </tr>
            <tr>
                <td class="fisrt">Exponential Moving Average</td>
                <td class="second"> {{ trn_ema }}</td>
            </tr>
            <tr>
                <td class="fisrt">Ichimoku Kinkō Hyō</td>
                <td class="second"> {{ trn_ich }}</td>
            </tr>
            <tr>
                <td class="fisrt">KST Oscillator</td>
                <td class="second"> {{ trn_kst }}</td>
            </tr>
            <tr>
                <td class="fisrt">MACD</td>
                <td class="second"> {{ trn_macd }}</td>
            </tr>
        </table>
    </div>
    </div>
        <div class="line"></div>
    <div class="final_signal">
        <div class="final_signal_writeup">Final Signal</div>
        <img class="final_signal_img" src="https://storage.googleapis.com/bshd_static/static/{{ score }}" >
    </div>
    </body>
{% endblock %}

bsh_user/templates/bsh_user/layout_User.html
{% load static %}

<head>
    <link rel="stylesheet" href="https://storage.googleapis.com/bshd_static/static/bsh_user/layout_User.css">
    <meta name="viewport" content="width=device-width" initial-scale="1.0">
</head>
<div class="header">
    <div class="nav-bar">
        <div class="BSH"><a href="{% url 'homepage:Homepage' %}"> <img
                src="https://storage.googleapis.com/bshd_static/static/homepage/BSH.svg" alt="BSH"></a>
        </div>
        <div class="hamburger"><img class="hamburger"
                                    src="https://storage.googleapis.com/bshd_static/static/homepage/investor.svg"
                                    alt="Hamburger"
                                    onclick="myFunction()">
            <div id="myDropdown" class="dropdown-content">
                <a href="{% url 'bsh_user:Userpage' %}">User Home</a>
                <a href="{% url 'logout' %}">Logout</a>
            </div>
        </div>
    </div>
</div>
<script>
    function myFunction() {
        document.getElementById("myDropdown").classList.toggle("show");
    }

    // Close the dropdown if the user clicks outside of it
    window.onclick = function (event) {
        if (!event.target.matches('.hamburger')) {
            var dropdowns = document.getElementsByClassName("dropdown-content");
            var i;
            for (i = 0; i < dropdowns.length; i++) {
                var openDropdown = dropdowns[i];
                if (openDropdown.classList.contains('show')) {
                    openDropdown.classList.remove('show');
                }
            }
        }
    }
</script>

<div class="index_prices">
    <div class="nav-index">
        <div class="NIFTY50">
            <ul class="NIFTY_table">
                <li class="NIFTY">NIFTY</li>
                <li class="NIFTY_price">{{ price_nifty }}</li>
                <li class="NIFTY_diff_red">{{ diffn_red }}</li>
                <li class="NIFTY_diff_green">{{ diffn_green }}</li>

            </ul>
        </div>
        <div class="SENSEX">
            <ul class="SENSEX_table">
                <li class="SENSEX">SENSEX</li>
                <li class="SENSEX_price">{{ price_sensex }}</li>
                <li class="SENSEX_diff_green">{{ diffs_green }}</li>
                <li class="SENSEX_diff_red">{{ diffs_red }}</li>

            </ul>
        </div>
        <div class="NB">
            <ul class="NB_table">
                <li class="NB">Stock Of The Day - {{ name }}</li>
                <li class="NB_price">{{ price_nb }}</li>
                <li class="NB_diff_green">{{ diffnb_green }}</li>
                <li class="NB_diff_red">{{ diffnb_red }}</li>
            </ul>
        </div>
    </div>
</div>


{% block content %}
{% endblock %}
<div class="footer">
    <ul class="social_media">
        <li class="ig_logo"><img src="https://storage.googleapis.com/bshd_static/static/homepage/IG logo.png"
                                 alt="ig_logo"></li>
        <li class="fb_logo"><img src="https://storage.googleapis.com/bshd_static/static/homepage/FB Logo.png"
                                 alt="fb_logo"></li>
        <li class="mail_logo"><img src="https://storage.googleapis.com/bshd_static/static/homepage/Gmail Logo.png"
                                   alt="mail_logo"></li>
    </ul>
</div>

bsh_user/templates/bsh_user/user_page_search.html
{% extends 'bsh_user/layout_User.html' %}
{% block content %}
{% load static %}
    <head>
        <title>Technical Analysis</title>
        <link rel="stylesheet" href="https://storage.googleapis.com/bshd_static/static/bsh_user/user_page_results.css">
    </head>
    <div class="search_results">Search Results</div>
    {% for index in indexs %}
        <form action="{% url 'bsh_user:AnalysisPage' %}" method="get">
            {% csrf_token %}
            <label>
                <input  type="hidden" name="Ticker" value="{{ index }}">
            </label>
            <input class="Co_name" type="submit" value="{{ index }}">
        </form>


    {% endfor %}
{% endblock %}