BSHDEV/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('homepage/', include('homepage.urls')),
    path('homepage/', include('django.contrib.auth.urls')),
    path('tech_analysis/', include('tech_analysis.urls')),
    path('user/', include('bsh_user.urls')),
]

homepage/urls.py
from django.urls import path
from . import views
from django.conf.urls import url

app_name = "homepage"
urlpatterns = [
    path('', views.homepage, name='Homepage'),
    path('our_goal', views.our_goal, name='Our_Goal'),
    path('our_inspiration', views.our_inspiration, name='Our_Inspiration'),
    path('what_do_we_do', views.what_do_we_do, name='What_do_we_do'),
    path('who_we_are', views.who_we_are, name='Who_we_are'),
    path('registration', views.register, name='Register'),

]

tech_analysis/urls.py
from django.urls import path
from . import views

app_name = "tech_analysis"
urlpatterns = [
    path('tech_analysis', views.analysis, name='Tech_Analysis'),
    path('search', views.results, name='Search_Results'),
]

tech_analysis/models.py
from django.db import models


class Conames(models.Model):
    Co_name = models.CharField(max_length=300)
    ticker = models.CharField(max_length=300)
    tick = models.CharField(max_length=300, default="")

    def __str__(self):
        return self.Co_name

tech_analysis/views.py
from django.shortcuts import render, HttpResponse
from homepage.index_prices import price_nb, price_sensex, price_bm, price_nifty, diffn_red, diffn_green, diffnb_red, \
    diffnb_green, diffs_red, diffs_green, diffbm_red, diffbm_green
import datetime as dt
import pandas_datareader.data as web
import ta
from statistics import mean, mode
from .models import Conames
from datetime import date
import json


def analysis(request):
    if request.method == 'GET':
        form = request.GET
        ticker = form.get("Ticker", "0")
        index = Conames.objects.get(Co_name=ticker).pk
        object_list = Conames.objects.only('ticker').get(pk=index).ticker
        start = dt.datetime(2017, 1, 1)
        end = date.today()
        df = web.DataReader(object_list, 'yahoo', start, end)
        close = df['Close']
        high = df['High']
        low = df['Low']
        volume = df['Volume']
        p = close[-1]
        old_price = close[-2]
        price = "%.2f" % p
        dif = ((p - old_price) / old_price) * 100
        diff = "%.2f" % dif
        if dif > 0:
            diff_green = "+" + diff + "%"
        else:
            diff_green = ""

        if dif < 0:
            diff_red = diff + "%"
        else:
            diff_red = ""

    def rs():
        r = ta.rsi(close, n=14, fillna=False)
        rsi = (r[-1])
        if 15.1 <= rsi <= 30:
            status = "Buy"
        elif rsi <= 15:
            status = "Strong Buy"
        elif 84.9 <= rsi >= 70:
            status = "Sell"
        elif rsi >= 85:
            status = "Strong Sell"
        else:
            status = "Hold"
        return status

    def ao():
        ao = ta.ao(high, low, s=5, len=34, fillna=False)
        AO = ao[-1]
        A = (ao[-10:])
        if 0 >= AO >= -0.5:
            def order():  # For ascending
                for i in range(len(A) - 1):
                    if A[i] - A[i + 1] > 0:
                        return False
                    return True

            if order():
                status1 = "Buy"
            else:
                status1 = "Sell"

        elif 0 <= AO <= 0.5:
            def order():  # For descending
                for i in range(len(A) - 1):
                    if A[i] - A[i + 1] < 0:
                        return False
                    return True

            if order():
                status1 = "Sell"
            else:
                status1 = "Buy"

        elif AO <= -1:
            status1 = "Buy"
        elif AO >= 1:
            status1 = "Sell"
        else:
            status1 = "Hold"
        return status1

    def mf():
        mfi = ta.money_flow_index(high, low, close, volume, n=14, fillna=False)
        MFI = mean(mfi[-7:])
        if MFI <= 20:
            status2 = "Buy"
        elif MFI <= 30:
            status2 = "Buy"
        elif MFI >= 80:
            status2 = "Sell"
        elif MFI >= 70:
            status2 = "Sell"
        else:
            status2 = "Hold"
        return status2

    def so():
        so = ta.stoch(high, low, close, n=14, fillna=False)
        SO = (so[-1])
        if SO <= 20:
            status3 = "Buy"
        elif SO <= 30:
            status3 = "Buy"
        elif SO >= 80:
            status3 = "Sell"
        elif SO >= 70:
            status3 = "Sell"
        else:
            status3 = "Hold"
        return status3

    def s_o():
        sos = ta.stoch_signal(high, low, close, n=14, d_n=3, fillna=False)
        SOS = (sos[-1])
        if SOS <= 20:
            status4 = "Buy"
        elif SOS <= 30:
            status4 = "Buy"
        elif SOS >= 80:
            status4 = "Sell"
        elif SOS >= 70:
            status4 = "Sell"
        else:
            status4 = "Hold"
        return status4

    def tsi():
        tsi = ta.tsi(close, r=25, s=13, fillna=False)
        TSI = tsi[-1]
        if TSI >= 20:
            status5 = "Buy"
        elif 5 <= TSI <= 20:
            status5 = "Buy"
        elif TSI <= 5:
            status5 = "Hold"
        elif -20 <= TSI <= -5:
            status5 = "Sell"
        elif TSI >= -20:
            status5 = "Sell"
        return status5

    def u_o():
        uo = ta.uo(high, low, close, s=7, m=14, len=28, ws=4.0, wm=2.0, wl=1.0, fillna=False)
        UO = uo[-1]
        if UO <= 10:
            status6 = "Buy"
        elif 10.1 <= UO <= 30:
            status6 = "Buy"
        elif 70 <= UO <= 90:
            status6 = "Sell"
        elif UO >= 90:
            status6 = "Sell"
        else:
            status6 = "Hold"
        return status6

    def w_r():
        wr = ta.wr(high, low, close, lbp=14, fillna=False)
        WR = wr[-1]
        if 0 >= WR >= 20:
            status7 = "Sell"
        elif -80 <= WR:
            status7 = "Buy"
        else:
            status7 = "Hold"
        return status7

    def cm():
        cmf = ta.chaikin_money_flow(high, low, close, volume, n=20, fillna=False)
        CMF = cmf[-1]

        if CMF > 1.5:
            vol_status_cmf = "Buy"
        elif 0 <= CMF <= 1.5:
            vol_status_cmf = "Buy"
        elif CMF == 0:
            vol_status_cmf = "Hold"
        elif -1.5 <= CMF <= 0:
            vol_status_cmf = "Sell"
        else:
            vol_status_cmf = "Sell"
        return vol_status_cmf

    def em():
        emv = ta.ease_of_movement(high, low, close, volume, n=20, fillna=False)
        EMV = emv[-1]
        if EMV >= 1.5:
            vol_status_emv = "Buy"
        elif -1.5 <= EMV <= 1.5:
            vol_status_emv = "Hold"
        else:
            vol_status_emv = "Sell"
        return vol_status_emv

    def f_i():
        fi = ta.force_index(close, volume, n=2, fillna=False)
        FI = fi[-1]
        if FI >= 0:
            vol_status_fi = "Buy"
        elif FI <= 0:
            vol_status_fi = "Sell"
        else:
            vol_status_fi = "Hold"
        return vol_status_fi

    def nv():
        nvi = ta.negative_volume_index(close, volume, fillna=False)
        ema255 = ta.ema_indicator(close, n=255, fillna=False)
        NVI = nvi[-1]
        E = ema255[-1]
        if NVI > E:
            vol_status_nvi = "Buy"
        elif NVI < E:
            vol_status_nvi = "Sell"
        else:
            vol_status_nvi = "Hold"
        return vol_status_nvi

    def ob():
        obv = ta.on_balance_volume(close, volume, fillna=False)
        OBV = obv[-10:]

        def order():  # For ascending
            for i in range(len(OBV) - 1):
                if OBV[i] - OBV[i + 1] > 0:
                    return False
                return True

        if order():
            vol_status_obv = "Buy"
        else:
            vol_status_obv = "Buy"
        return vol_status_obv

    def adi():
        add = ta.acc_dist_index(high, low, close, volume, fillna=False)
        a = add[-1]
        ad = add[-7:]

        if a <= 1000:
            def order():  # For ascending
                for i in range(len(ad) - 1):
                    if ad[i] - ad[i + 1] > 0:
                        return False
                    return True

            if order():
                vol_status_add = "Buy"
            else:
                vol_status_add = "Sell"

        else:
            vol_status_add = "No signal"

        return vol_status_add

    def at():
        atr = ta.average_true_range(high, low, close, n=14, fillna=False)

        if atr[-1] >= 1.5 + mean(atr[-10:]):
            vot_status_atr = "Buy"
        elif atr[-1] <= mean(atr[-10:] - 1.5):
            vot_status_atr = "Sell"
        else:
            vot_status_atr = "Hold"
        return vot_status_atr

    def bb():
        bbhb = ta.bollinger_hband(close, n=20, ndev=2, fillna=False)
        bbhb_ind = ta.bollinger_hband_indicator(close, n=20, ndev=2, fillna=False)
        bblb = ta.bollinger_lband(close, n=20, ndev=2, fillna=False)
        bblb_ind = ta.bollinger_lband_indicator(close, n=20, ndev=2, fillna=False)
        bbmavg = ta.bollinger_mavg(close, n=20, fillna=False)
        sub = bbhb[-1] - close[-1]
        sub2 = close[-1] - bblb[-1]

        if sub > sub2:
            vot_status_bb = "Buy"
        elif sub < sub2:
            vot_status_bb = "Sell"
        else:
            vot_status_bb = "Hold"
        return vot_status_bb

    def dch():
        dch = ta.donchian_channel_hband(close, n=20, fillna=False)
        dchi = ta.donchian_channel_hband_indicator(close, n=20, fillna=False)
        dcl = ta.donchian_channel_lband(close, n=20, fillna=False)
        dcli = ta.donchian_channel_lband_indicator(close, n=20, fillna=False)

        if close[-1] == dch[-1]:
            vot_status_dc = "Strong Sell"
        elif dch[-1] > close[-1] > dch[-1] - 2:
            vot_status_dc = "Sell"
        elif dcl[-1] == close[-1]:
            vot_status_dc = "Strong Buy"
        elif dcl[-1] < close[-1] <= dcl[-1] + 2:
            vot_status_dc = "Buy"
        else:
            vot_status_dc = "Hold"
        return vot_status_dc

    def adx():
        adx = ta.adx(high, low, close, n=14, fillna=False)
        adxn = ta.adx_neg(high, low, close, n=14, fillna=False)
        adxp = ta.adx_pos(high, low, close, n=14, fillna=False)

        if adxp[-1] > adxn[-1]:
            trn_adx_status = " Buy"
        elif adxp[-1] < adxn[-1]:
            trn_adx_status = " Sell"
        else:
            trn_adx_status = " Hold"
        return trn_adx_status

    def ai():
        aid = ta.aroon_down(close, n=25, fillna=False)
        aiu = ta.aroon_up(close, n=25, fillna=False)
        if aiu[-1] > aid[-1]:
            trn_ai_status = "Buy"
        elif aiu[-1] < aid[-1]:
            trn_ai_status = "Sell"
        else:
            trn_ai_status = "Hold"
        return trn_ai_status

    def c():
        cci = ta.cci(high, low, close, n=20, c=0.015, fillna=False)
        cc = cci[-1]

        if 0 <= cc <= 50:
            trn_cci_status = "Buy"
        elif 50.1 <= cc <= 100:
            trn_cci_status = "Hold"
        elif 100.1 <= cc:
            trn_cci_status = "Sell"

tech_analysis/templates/tech_analysis/results.html
{% extends 'homepage/layout.html' %}
{% block content %}
{% load static %}
    <head>
        <title>Technical Analysis</title>
        <link rel="stylesheet" href="https://storage.googleapis.com/bshd_static/static/tech_analysis/results.css">
    <meta name="viewport" content="width=device-width" initial-scale="1.0">
    </head>
    <div class="search_results">Search Results</div>
    <div class="results">
    {% for index in indexs %}
        <form class="ticker" action="{% url 'tech_analysis:Tech_Analysis' %}" method="get">
            {% csrf_token %}
            <label>
                <input  type="hidden" name="Ticker" value="{{ index }}">
            </label>
            <input class="Co_name" type="submit" value="{{ index }}">
        </form>


    {% endfor %}
    </div>
{% endblock %}

tech_analysis/templates/tech_analysis/tech_analysis.html
{% extends 'homepage/layout.html' %}
{% block content %}
    {% load static %}
    <head>
        <title>Technical Analysis</title>
        <link rel="stylesheet" href="https://storage.googleapis.com/bshd_static/static/tech_analysis/tech_analysis.css">
        <meta name="viewport" content="width=device-width" initial-scale="1.0">
    </head>
    <div class="head">
        Technical Analysis
    </div>
    <div class="coname">
        <ul class="ticker_table">
            <li class="ticker_name">{{ ticker }}-</li>
            <li class="ticker_price">{{ price }}</li>
            <li class="diff_green">{{ diff_green }}</li>
            <li class="diff_red">{{ diff_red }}</li>
        </ul>

    </div>

    <div class="tables">
        <table class="momentum">
            <tr>
                <th>Momentum</th>
                <th>Signal</th>
            </tr>
            <tr>
                <td class="first">Relative Strength Index</td>
                <td class="second"> {{ mom_rsi }} </td>
            </tr>
            <tr>
                <td class="first">Awesome Oscillator</td>
                <td class="second"> {{ mom_ao }}</td>
            </tr>
            <tr>
                <td class="first">Money Flow Index</td>
                <td class="second"> {{ mom_mf }}</td>
            </tr>
            <tr>
                <td class="first">Stochastic Oscillator</td>
                <td class="second"> {{ mom_so }}</td>
            </tr>
            <tr>
                <td class="first">True Strength Index</td>
                <td class="second"> {{ mom_tsi }}</td>
            </tr>
            <tr>
                <td class="first">Ultimate Oscillator</td>
                <td class="second"> {{ mom_uo }}</td>
            </tr>
            <tr>
                <td class="first">Williams %R</td>
                <td class="second"> {{ mom_wr }}</td>
            </tr>
            <tr>
                <td colspan="2">

                    <img class="mom_final" src="https://storage.googleapis.com/bshd_static/static/{{ mom_final }}">

                </td>
            </tr>

        </table>


        <table class="Volume">
            <tr>
                <th>Volume</th>
                <th>Signal</th>
            </tr>
            <tr>
                <td class="first">Chaikin Money Flow</td>
                <td class="second"> {{ vol_cm }}</td>
            </tr>
            <tr>
                <td class="first">Ease of movement</td>
                <td class="second"> {{ vol_em }}</td>
            </tr>
            <tr>
                <td class="first">Force Index</td>
                <td class="second"> {{ vol_fi }}</td>
            </tr>
            <tr>
                <td class="first">Negative Volume Index</td>
                <td class="second"> {{ vol_nv }}</td>
            </tr>
            <tr>
                <td class="first">On-balance volume</td>
                <td class="second"> {{ vol_ob }}</td>
            </tr>
            <tr>
                <td class="first">Accumulation/Distribution Index</td>
                <td class="second"> {{ vol_adi }}</td>
            </tr>
            <tr>
                <td colspan="2">
                    <img class="vol_final" src="https://storage.googleapis.com/bshd_static/static/{{ vol_final }}">
                </td>

            </tr>
        </table>



        <table class="Volatility">
            <tr class="head_table">
                <th>Volatility</th>
                <th>Signal</th>
            </tr>
            <tr>
                <td class="first">Average True Range</td>
                <td class="second"> {{ vot_atr }}</td>
            </tr>
            <tr>
                <td class="first">Bollinger Bands</td>
                <td class="second"> {{ vot_bb }}</td>
            </tr>
            <tr>
                <td class="first">Donchian channel</td>
                <td class="second"> {{ vot_dch }}</td>
            </tr>
            <tr>
                <td colspan="2">
                    <img class="vot_final" src="https://storage.googleapis.com/bshd_static/static/{{ vot_final }}">
                </td>
            </tr>
        </table>

        <table class="Trend">
            <tr>
                <th>Trend</th>
                <th>Signal</th>
            </tr>
            <tr>
                <td class="first">Average Directional Movement Index</td>
                <td class="second"> {{ trn_adx }}</td>
            </tr>
            <tr>
                <td class="first">Aroon Indicator</td>
                <td class="second"> {{ trn_ai }}</td>
            </tr>
            <tr>
                <td class="first">Commodity Channel Index</td>
                <td class="second"> {{ trn_cci }}</td>
            </tr>
            <tr>
                <td class="first">Detrended Price Oscillator</td>
                <td class="second"> {{ trn_dpo }}</td>
            </tr>
            <tr>
                <td class="first">Exponential Moving Average</td>
                <td class="second"> {{ trn_ema }}</td>
            </tr>
            <tr>
                <td class="first">Ichimoku Kinkō Hyō</td>
                <td class="second"> {{ trn_ich }}</td>
            </tr>
            <tr>
                <td class="first">KST Oscillator</td>
                <td class="second"> {{ trn_kst }}</td>
            </tr>
            <tr>
                <td class="first">MACD</td>
                <td class="second"> {{ trn_macd }}</td>
            </tr>
            <tr>
                <td colspan="2">
                    <img class="trn_final" src="https://storage.googleapis.com/bshd_static/static/{{ trn_final }}">
                </td>
            </tr>
        </table>

    </div>
    <div class="more">
        <a class="more" href="{% url 'homepage:Register' %}">Detailed Analysis</a>
    </div>
{% endblock %}