BSHDEV/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('homepage/', include('homepage.urls')),
    path('homepage/', include('django.contrib.auth.urls')),
    path('tech_analysis/', include('tech_analysis.urls')),
    path('user/', include('bsh_user.urls')),
]

homepage/urls.py
from django.urls import path
from . import views
from django.conf.urls import url

app_name = "homepage"
urlpatterns = [
    path('', views.homepage, name='Homepage'),
    path('our_goal', views.our_goal, name='Our_Goal'),
    path('our_inspiration', views.our_inspiration, name='Our_Inspiration'),
    path('what_do_we_do', views.what_do_we_do, name='What_do_we_do'),
    path('who_we_are', views.who_we_are, name='Who_we_are'),
    path('registration', views.register, name='Register'),

]

tech_analysis/urls.py
from django.urls import path
from . import views

app_name = "tech_analysis"
urlpatterns = [
    path('tech_analysis', views.analysis, name='Tech_Analysis'),
    path('search', views.results, name='Search_Results'),
]

homepage/models.py
from django.db import models

class Homepage_db(models.Model,):
    hco_name = models.CharField(max_length=300, default='')
    htic_name = models.CharField(max_length=300, default='')
    hco_logo = models.ImageField(default='')

    def __str__(self):
        return self.hco_name

homepage/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm


class RegistrationForm(UserCreationForm):
    email = forms.EmailField(required=True)

    class Meta:
        model = User
        fields = (
            'username',
            'first_name',
            'last_name',
            'email',
            'password1',
            'password2',
        )

    def save(self, commit=True):
        user = super(RegistrationForm, self).save(commit=False)
        user.first_name = self.cleaned_data['first_name']
        user.last_name = self.cleaned_data['last_name']
        user.email = self.cleaned_data['email']

        if commit:
            user.save()

        return User

homepage/views.py
from django.shortcuts import render, redirect, HttpResponseRedirect, HttpResponse
from django.contrib.auth.forms import UserCreationForm, forms
from homepage.index_prices import args
from homepage.forms import RegistrationForm
from .models import Homepage_db
import datetime as dt
from datetime import date
import pandas_datareader.data as web
from tech_analysis.models import Conames
import json
from django.contrib.auth import login
from azure.cognitiveservices.search.newssearch import NewsSearchAPI
from azure.cognitiveservices.language.textanalytics import TextAnalyticsClient
from msrest.authentication import CognitiveServicesCredentials
import os


def homepage(request):
    global x, rows, signal
    start = dt.datetime(2017, 1, 1)
    end = date.today()
    dfn = web.DataReader("^NSEI", 'yahoo', start, end)

    closen = dfn['Close']
    pricen1 = closen[-1]
    pricen2 = closen[-2]
    pdiffn = ((pricen1 - pricen2) / pricen2) * 100
    diffn = "%.2f" % pdiffn
    price_nifty = "%.2f" % pricen1
    if pdiffn > 0:
        diffn_green = "+" + diffn + "%"
    else:
        diffn_green = ""

    if pdiffn < 0:
        diffn_red = diffn + "%"
    else:
        diffn_red = ""

    dfs = web.DataReader("^BSESN", 'yahoo', start, end)
    closes = dfs['Close']
    prices1 = closes[-1]
    prices2 = closes[-2]
    pdiffs = ((prices1 - prices2) / prices2) * 100
    diffs = "%.2f" % pdiffs
    price_sensex = "%.2f" % prices1
    if pdiffs >= 0:
        diffs_green = "+" + diffs + "%"
    else:
        diffs_green = ""

    if pdiffs <= 0:
        diffs_red = diffs + "%"
    else:
        diffs_red = ""

    dfnb = web.DataReader("^NSEBANK", 'yahoo', start, end)
    closenb = dfnb['Close']
    pricenb1 = closenb[-1]
    pricenb2 = closenb[-2]
    pdiffnb = ((pricenb1 - pricenb2) / pricenb2) * 100
    diffnb = "%.2f" % pdiffnb
    if pdiffnb > 0:
        diffnb_green = "+" + diffnb + "%"
    else:
        diffnb_green = ""

    if pdiffnb < 0:
        diffnb_red = diffnb + "%"
    else:
        diffnb_red = ""
    price_nb = "%.2f" % pricenb1

    dfbm = web.DataReader("BSE-MIDCAP.BO", 'yahoo', start, end)
    closebm = dfbm['Close']
    pricebm1 = closebm[-1]
    pricebm2 = closebm[-2]
    pdiffbm = ((pricebm1 - pricebm2) / pricebm2) * 100
    diffbm = "%.2f" % pdiffbm
    if pdiffbm > 0:
        diffbm_green = "+" + diffbm + "%"
    else:
        diffbm_green = ""

    if pdiffbm < 0:
        diffbm_red = diffbm + "%"
    else:
        diffbm_red = ""
    price_bm = "%.2f" % pricebm1
    tickers = ['LT.BO', 'ITC.NS', 'RELIANCE.NS', 'WIPRO.BO', 'TCS.NS']
    stocks = ["Larsen & Toubro", "ITC Limited", "Reliance Industries", "Wipro", "TATA Consultancy Services"]
    closeps = []
    x = []
    price_diff_green = []
    price_diff_red = []
    hpbar = []
    signal = []
    for ticker in tickers:
        start = dt.datetime(2019, 1, 1)
        end = date.today()
        df = web.DataReader(ticker, 'yahoo', start, end)
        close = df['Close']
        price_diff = ((close[-1] - close[-2]) / close[-2]) * 100
        if price_diff > 0:
            price_diff_green.append("+" + "%.2f" % price_diff + "%")
        else:
            price_diff_green.append("")

        if price_diff < 0:
            price_diff_red.append("%.2f" % price_diff + "%")
        else:
            price_diff_red.append("")
        closeps.append("%.2f" % close[-1])
        x.append(Homepage_db.objects.only('hco_logo').get(htic_name=ticker).hco_logo)
        subscription_key = "d225b3f12aab446aa34af931359edbe0"
        search_term = ticker

        client = NewsSearchAPI(CognitiveServicesCredentials(subscription_key))
        news_result = client.news.search(query=search_term, market="en-us", count=10)

        if news_result.value:

            first_news_result = news_result.value[0]
            data = format(first_news_result.description)



            # print("news name: {}".format(first_news_result.name))
            #
            # print("news description: {}".format(first_news_result.description))


        else:
            HttpResponse("NIL")

        # --------------------------------------------

        TEXT_ANALYTICS_SUBSCRIPTION_KEY = '4d1d3697dc8548b59163e2592b22beb7'
        subscription_key = TEXT_ANALYTICS_SUBSCRIPTION_KEY

        TEXT_ANALYTICS_ENDPOINT = 'https://analytics4sentiment.cognitiveservices.azure.com/'
        endpoint = TEXT_ANALYTICS_ENDPOINT

        credentials = CognitiveServicesCredentials(subscription_key)
        text_analytics_client = TextAnalyticsClient(
            endpoint=endpoint, credentials=credentials)

        client = text_analytics_client

        documents = [
            {"id": "1", "language": "en", "text": data},
                   
        ]

        response = client.sentiment(documents=documents)
        res = []
        for document in response.documents:
            res.append(float(format(document.score)))

        res_mean = (sum(res) * 100)

        if res_mean > 80:
            hpbar.append("StrongBuy_hpbar.svg")
            signal.append("Strong Buy")
        elif 80 > res_mean > 60:
            hpbar.append("Buy_hpbar.svg")
            signal.append("Buy")
        elif 60 > res_mean > 35:
            hpbar.append("Hold_hpbar.svg")
            signal.append("Hold")
        elif 20 > res_mean > 35:
            hpbar.append("Sell_hpbar.svg")
            signal.append("Sell")
        else:
            hpbar.append("StrongSell_hpbar.svg")
            signal.append("Strong Sell")

    rows = zip(x, closeps, price_diff_green, price_diff_red, hpbar, signal, stocks)

    return render(request, 'homepage/homepage.html',
                  {"rows": rows, 'price_nifty': price_nifty, 'diffn_green': diffn_green, 'diffn_red': diffn_red,
                   'price_sensex': price_sensex,
                   'diffs_red': diffs_red, 'diffs_green': diffs_green, 'price_nb': price_nb,
                   'diffnb_green': diffnb_green,
                   'diffnb_red': diffnb_red, 'price_bm': price_bm, 'diffbm_green': diffbm_green,
                   'diffbm_red': diffbm_red})


def how_it_works(request):
    return render(request, 'homepage/how_it_works.html', args)


def our_goal(request):
    return render(request, 'homepage/our_goal.html', args)


def our_inspiration(request):
    return render(request, 'homepage/our_inspiration.html', args)


def what_do_we_do(request):
    return render(request, 'homepage/What_do_we_do.html', args)


def who_we_are(request):
    return render(request, 'homepage/who_we_are.html', args)


def register(request):
    if request.method == "POST":
        form = RegistrationForm(request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect('login')
        else:
            return HttpResponse("Ooopss!! Something was wrong with your information. Please go back and try again.")
    else:
        form = RegistrationForm()

        arg = {'form': form}
        return render(request, 'homepage/register.html', arg)

homepage/templates/homepage/What_do_we_do.html
{% extends 'homepage/layout.html' %}
{%  block content %}
{% load static %}
    <head>
        <link rel="stylesheet" href="https://storage.googleapis.com/bshd_static/static/homepage/our_goal.css">
        <title>What Do We Do</title>
    </head>
    <body>
        <div class=" write_up">
            <h1>What Do We Do</h1>
            <p>Our Algorithm analyses various factors affecting a stock price and delivers a Buy, Sell or Hold signal to the user.</p>
            <p>The purpose of the algorithm is to cut down the time taken in research and analysis.</p>
            <p>Along with many quantitative factors our algorithm also analyses factors like news sentiment of a stock and its market trends. </p>
        </div>
    </body>
{% endblock %}

homepage/templates/homepage/homepage.html
{% extends 'homepage/layout.html' %}
{%  block content %}
{% load static %}
<head>
    <link rel="stylesheet" href="https://storage.googleapis.com/bshd_static/static/homepage/homepage.css">
    <meta name="viewport" content="width=device-width" initial-scale="1.0">
    <title>Buy Sell Hold</title>
</head>


<div class="background">
    <div class="tag_line">Making Stock Market Decisions Easy!</div>
</div>
    <div class="closeps">
        <div class="featured_stocks">Featured Stocks</div>
            {% for x, closeps,price_diff_green, price_diff_red, hpbar, signal, stocks in rows %}
                <div class="Hpbar"><img class="hpbar" src="https://storage.googleapis.com/bshd_static/static/homepage/{{ hpbar }}">
                    <img class="logos" src="https://storage.googleapis.com/bshd_static/static/homepage/{{ x }}">
                    <table class="nums">
                        <tr>
                    <td class="stocks">{{ stocks }}</td>
                    <td class="price">{{ closeps }}</td>
                    <td class="price_green ">{{ price_diff_green }}</td>
                    <td class="price_red">{{ price_diff_red }}</td>
                        </tr>
                    </table>
                </div>
                <table class="fs_table">
                <tr>
                    <td class="stocks">{{ stocks }}</td>
                    <td class="price">{{ closeps }}</td>
                    <td class ="price_green ">{{ price_diff_green }}</td>
                    <td class="price_red">{{ price_diff_red }}</td>
                    <td class="signal">{{ signal }}</td>
                </tr>
                </table>
            {% endfor %}

    </div>
<div class="explore"><a class="explore" href="{% url 'homepage:Register' %}"> Explore</a></div>

{% endblock %}

homepage/templates/homepage/how_it_works.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

homepage/templates/homepage/layout.html
{% load static %}

<head>
    <link rel="stylesheet" href="https://storage.googleapis.com/bshd_static/static/homepage/layout.css">
    <script src="https://storage.googleapis.com/bshd_static/static/homepage/layout.js" type="text/javascript"></script>
    <meta name="viewport" content="width=device-width" initial-scale="1.0">
</head>
<body>
<div class="header">
    <div class="nav-bar">
    <div class="BSH"><a href="{% url 'homepage:Homepage' %}"> <img src="https://storage.googleapis.com/bshd_static/static/homepage/BSH.svg" alt="BSH"></a></div>
    <div class="hamburger"><img class="hamburger" src="https://storage.googleapis.com/bshd_static/static/homepage/investor.svg" alt="Hamburger" onclick="myFunction()">
    <div id="myDropdown" class="dropdown-content">
        <a href="{% url 'login' %}">Login</a>
        <a href="{% url 'homepage:Register' %}">Register</a>
    </div>
    </div>
    </div>
    </div>
<script>
function myFunction() {
  document.getElementById("myDropdown").classList.toggle("show");
}

// Close the dropdown if the user clicks outside of it
window.onclick = function(event) {
  if (!event.target.matches('.hamburger')) {
    var dropdowns = document.getElementsByClassName("dropdown-content");
    var i;
    for (i = 0; i < dropdowns.length; i++) {
      var openDropdown = dropdowns[i];
      if (openDropdown.classList.contains('show')) {
        openDropdown.classList.remove('show');
      }
    }
  }
}
</script>

<div class="index_prices">
    <div class="nav-index">
    <div class="NIFTY50">
        <ul class="NIFTY_table">
            <li class="NIFTY">NIFTY</li>
            <li class="NIFTY_price">{{ price_nifty }}</li>
            <li class="NIFTY_diff_red">{{ diffn_red }}</li>
            <li class="NIFTY_diff_green">{{ diffn_green }}</li>

        </ul>
    </div>
    <div class="SENSEX">
        <ul class="SENSEX_table">
            <li class="SENSEX">SENSEX</li>
            <li class="SENSEX_price">{{ price_sensex }}</li>
            <li class="SENSEX_diff_green">{{ diffs_green }}</li>
            <li class="SENSEX_diff_red">{{ diffs_red }}</li>

        </ul>
    </div>
    <div class="NB">
        <ul class="NB_table">
            <li class="NB">NIFTYBANK</li>
            <li class="NB_price">{{ price_nb }}</li>
            <li class="NB_diff_green">{{ diffnb_green }}</li>
            <li class="NB_diff_red">{{ diffnb_red }}</li>
        </ul>
    </div>

    <div class="BM" id="BM">
        <ul class="BM_table">
            <li class="BM">BSEMIDCAP</li>
            <li class="BM_price">{{ price_bm }}</li>
            <li class="BM_diff_green">{{ diffbm_green }}</li>
            <li class="BM_diff_red">{{ diffbm_red }}</li>
        </ul>
    </div>
        </div>
</div>
<div><form action="{% url 'tech_analysis:Search_Results' %}" method="get" autocomplete="on">
         <div class="autocomplete">

            <label>
                <input class="enter_ticker" type="text" name="Ticker" id="myInput"  placeholder="Enter Ticker">
                <img class="search-label-icon" src="https://storage.googleapis.com/bshd_static/static/homepage/path.png" alt="search" id="input_img">
            </label>
            <input class="technical_analysis" type="image" src="https://storage.googleapis.com/bshd_static/static/homepage/Submit.png" >
            </div>
        </form>
</div>

<div class="line">
</div>
<div class="sidebar" onclick="sidebar_pullout()">
<div class="arrowleft" onclick="sidebar_pullout()"><img src="https://storage.googleapis.com/bshd_static/static/homepage/Arrow Left.png" alt="Arrowleft" >
    </div>
        <div class="submenu" id="submenu">
                <a class="head">BUY SELL HOLD</a>
                <a class="about" href="{% url 'homepage:Our_Goal' %}">Our Goal</a>
                <a class="about" href="{% url 'homepage:Our_Inspiration' %}">Our Inspiration</a>
                <a class="about" href="{% url 'homepage:Who_we_are' %}">Who We Are</a>
                <a class="about" href="{% url 'homepage:What_do_we_do' %}">What Do We Do</a>
        </div>

</div>
{% block content %}
{% endblock %}
<div class="footer">
    <table class="social_media">
        <tr>
    <td class="ig_logo"><img src="https://storage.googleapis.com/bshd_static/static/homepage/IG logo.png" alt="ig_logo"></td>
    <td class="fb_logo"><img src="https://storage.googleapis.com/bshd_static/static/homepage/FB Logo.png" alt="fb_logo"></td>
    <td class="mail_logo"><img src="https://storage.googleapis.com/bshd_static/static/homepage/Gmail Logo.png" alt="mail_logo"></td>
    </tr>
    </table>
</div>

</body>

homepage/templates/homepage/our_goal.html
{% extends 'homepage/layout.html' %}
{%  block content %}
{% load static %}
    <head>
        <link rel="stylesheet" href="https://storage.googleapis.com/bshd_static/static/homepage/our_goal.css">
        <title>Our Goal</title>
    </head>
    <body>
        <div class=" write_up">
            <h1> Our Goal</h1>
            <p>We are working towards making the decision making process of a stock market investor easy, more informed and less time consuming. </p>
            <p>We aim to provide quick analysis which is supported by high quality of technology and accuracy.</p>
        </div>
    </body>
{% endblock %}

homepage/templates/homepage/our_inspiration.html
{%  extends 'homepage/layout.html' %}
{%  block content %}
    {% load static %}
    <head>
        <link rel="stylesheet" href="https://storage.googleapis.com/bshd_static/static/homepage/our_goal.css">
        <title>Our Inspiration</title>
    </head>
    <body>
        <div class=" write_up">
            <h1>Our Inspiration</h1>
            <p>We are inspired by the idea of enabling our users to be regular investors in the stock market.</p>
            <p>We are inspired everyday by the advancements that are being made in the Fintech Sector and everything around it.</p>
            <p>We look up to this community of Fintech Sector and ideas they are exploring to help us continue the work we're doing to deliver our purpose: Making Stock Market Decisions Easy.  </p>
        </div>
    </body>
{% endblock %}

homepage/templates/homepage/register.html
{% load static %}
<head>
    <title>Register</title>
    <link rel="stylesheet" href="https://storage.googleapis.com/bshd_static/static/homepage/register.css">
    <meta content="width=device-width, initial-scale=1" name="viewport" />
</head>
<body>
<div class="head">Register
</div>
<div class="line">
</div>

    <div class="container">
<form method="post">

        {% csrf_token %}
        <div class="register_table">
            <div class="username">Username
                <div class="input_username">{{ form.username }}</div> </div>

            <div class="first_name">First Name
                <div class="input_firstname">{{ form.first_name }}</div></div>

            <div class="last_name">Last Name
                <div class="input_lastname">{{ form.last_name }}</div></div>

            <div class="email">Email
                <div class="input_email">{{ form.email }}</div></div>

            <div class="password1">Password
                <div class="input_password1">{{ form.password1 }}</div><p> (8 Characters, Different from other info., Not too Common)</p></div>

            <div class="password2">Confirm Password
                <div class="input_password2">{{ form.password2 }}</div></div>
        </div>
        <button class="button" type="submit">Register</button>
    </form>
        <div class="login_user"> Already a user? <a class="login_user" href="{% url 'login' %}">Login</a></div>
    </div>

</body>

homepage/templates/homepage/who_we_are.html
{% extends 'homepage/layout.html' %}
{%  block content %}
{% load static %}
    <head>
        <link rel="stylesheet" href="https://storage.googleapis.com/bshd_static/static/homepage/our_goal.css">
        <title>Who We Are</title>
    </head>
    <body>
        <div class=" write_up">
            <h1>Who We Are</h1>
            <p>We are your go to website for stock analysis.</p>
        </div>
    </body>
{% endblock %}